parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\Pet\CreatePet\CreatePetHandler:
        arguments:
            $petApiClient: '@App\Infrastructure\PetstoreClient'
            $validator: '@validator'

    App\Application\Pet\GetPetById\GetPetByIdHandler:
        arguments:
            $petApiClient: '@App\Infrastructure\PetstoreClient'

    App\Application\Pet\UpdatePet\UpdatePetHandler:
        arguments:
            $petApiClient: '@App\Infrastructure\PetstoreClient'
            $validator: '@validator'

    App\Application\Pet\DeletePet\DeletePetHandler:
        arguments:
            $petApiClient: '@App\Infrastructure\PetstoreClient'

    App\Application\Pet\FindPetsByStatus\FindPetsByStatusHandler:
        arguments:
            $petApiClient: '@App\Infrastructure\PetstoreClient'

    App\Infrastructure\PetstoreClient:
        arguments:
            $baseUrl: '%env(PETSTORE_BASE_URL)%'
