parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Domain\Pet\PetApiClientInterface: '@App\Infrastructure\DoctrinePetRepository'

    App\Application\Pet\CreatePet\CreatePetHandler:
        arguments:
            $validator: '@validator'

    App\Application\Pet\UpdatePet\UpdatePetHandler:
        arguments:
            $validator: '@validator'
